name: Test2

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # - run: npm install -g serve
      - run: node ./b.js
      # - run: serve .
